spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher # Swagger 설정을 위한 설정
  profiles:
    active: "dev"
  jpa:
    show-sql: true
    properties:
      format_sql: true
logging:
  level:
    root: info
---
spring:
  config:
    activate:
      on-profile: "dev"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/gdsc_practice?serverTimeZone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
---
spring:
  config:
    activate:
      on-profile: "test"
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
  datasource:
    url: 'jdbc:h2:mem:test'
    username: root
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

